server.port=8084

spring.datasource.url=jdbc:postgresql://db.hxyocwbfylhajfdvmmdv.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Bhagya@Heshani123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.security.oauth2.client.registration.google.client-id=1054247134298-5r3upf4hs6p52g3kom0m8dufekf84a8h.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email


