server.port=8084

spring.datasource.url=jdbc:postgresql://db.hxyocwbfylhajfdvmmdv.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Bhagya@Heshani123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration





